### ISSUE TITLE
log as a part of reporter

### ISSUE THREAD

**Issue by DeChrish** [allure-framework/mocha-allure-reporter#10]
how to add extra logs as apart of allure report

**Comment by just-boris** [comment]
As it done in [example project](https://github.com/allure-examples/mocha-allure-example), we recomend use [mocha-multi](https://github.com/glenjamin/mocha-multi) reporter.
Also see how we run it:

```
multi='progress=- mocha-allure-reporter=-' mocha
```

Does it work for you.

**Comment by DeChrish** [comment]
@just-boris  How to use it in mocha-grunt

**Comment by just-boris** [comment]
I didn't find `mocha-grunt`, but I guess you are using [grunt-simple-mocha](https://github.com/yaymukund/grunt-simple-mocha).

You need to replace reporter in their example configuration:

```js
grunt.initConfig({
  simplemocha: {
    options: {
      reporter: 'multi'
    },
    all: { src: ['test/**/*.js'] }
  }
});
```

Then you need to pass settings to mocha-multi. It accepts them as environment variable. Add them into your test command:

```
multi='progress=- mocha-allure-reporter=-' grunt test
```
(I assume that you run tests with `grunt test` command)

You can read more about mocha-multi configuration syntax in [its documentation](https://github.com/glenjamin/mocha-multi#choosing-reporters)

**Comment by just-boris** [comment]
Closing the issue, beause it is rather question than lack of features in our reporter.
