### ISSUE TITLE
Test suite empty

### ISSUE THREAD

**Issue by michaelDomingues** [allure-framework/mocha-allure-reporter#11]
Hi,

I assembled a project with WDIO+Mocha+Gulp+Allure and everything is fine except setting allure steps, features and so on. Debugging Allure suites is empty.

Can I, inside a test suite, set Allure suites ? 

allure-js-commons dependency has a startSuite() function mas I don't have access to it through my allure variable: undefined function by the compiler.

**Comment by just-boris** [comment]
Hello. How do you run tests?

We have an [example project](https://github.com/allure-examples/mocha-allure-example). Also, there are some tests with webdriver.io: https://github.com/allure-examples/mocha-allure-example/blob/master/test/webdriver-io.spec.js

How does it match with your setup?

**Comment by michaelDomingues** [comment]
Let me break this in parts:

Gulp:
my.con.js is a wide test runner file where I specify my tests in **specs** field. 
```
gulp.task('MyTest', function(done) {
    return gulp.src('confs/my.conf.js')\
        .pipe(webdriver())
        .on('error', function() {
            done();
        });
});
```
wide configs:

```
...
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
        reporter: 'mocha-allure-reporter',
        reporterOptions: {
            targetDir: 'allure-results'
        }
    },
...
```

Test file:
**browser** is my client, a global. 
As allure it is!

```
...
describe('Store', function() {
    it('should enter a space', function(done) {
        allure.createStep('STEP1', function(query) {});
        allure.story('XPTO');

        browser
            .click('//*[@id="sidebar"]/div/div[1]/div[2]/div[1]/div[1]')
            .setValue('//*[@id="sidebar"]/div/div[1]/div[2]/div[1]/div[1]/input', 11)
            .keys('Enter')
            .call(done);
  
    });
});
...
```

Printing allure var:

```
{ _allure: Allure { suites: [], options: { targetDir: 'allure-results' } } }
```

**Comment by just-boris** [comment]
Well, it got this. You are using mocha inside the [gulp-webdriver](https://github.com/webdriverio/gulp-webdriver). But this reporter intended to use with standalone mocha.

It is not expected usage, we have a special reporter for this case: [wdio-allure-reporter](https://github.com/webdriverio/wdio-allure-reporter). It has specially made for use with webdriver.io test launcher.

So, you should install it and change your wdio config to the following

```js
    specs: ['../test.js']
    framework: 'mocha',
    //note, reporter section is now on top-level
    reporters: ['dot', 'allure'],
    reporterOptions: {
        outputDir: './allure-results'
    },
```

Wdio launcher has some specifics, so you don't need to create steps using `allure.createStep`. Instead, every webdriver command will be recorded a step. If you want to create custom step – just create a custom command.

**Comment by michaelDomingues** [comment]
@just-boris thank you for the fast reply. 
Ok, I see the point! It makes sense using that one for wdio.

Even with the conf changes you suggested and the wdio-allure-reporter installed, now I got a problem with global access to allure. It can't find it  :/

Is there any way? I've already open an issue in the past with that problem.

**Comment by just-boris** [comment]
Wow, that's the interesting question. Webdriver.io launcher has a special architecture different than classical mocha tests. They are running every test suite in a separate process. So that's why you can reach `allure` object.

But wdio-allure-reporter is also designed that you don't need to use Allure directly. Why do you need access to it?

**Comment by michaelDomingues** [comment]
If the allure reports using wdio-allure-reporter are good enough, sincerely I don't need to access `allure` object by no reasons.

Still why don't  wdio-allure-reporter works ? I got no reports..

**Comment by just-boris** [comment]
Maybe because of it: https://github.com/webdriverio/wdio-allure-reporter/issues/5

It is a valid issue, I just didn't have a time to keep it moving.

**Comment by michaelDomingues** [comment]
Funny is, if you run directly with wdio: [https://github.com/christian-bromann/wdio-demo](url) it works.

**Comment by just-boris** [comment]
Webdriver.io v4 now is out. Allure intended to work only with latest version.

Closing this as a duplicate webdriverio/wdio-allure-reporter#5. If you have something to add, please add it there to not split up the discussion.

**Comment by cheungkayip** [comment]
@just-boris 
in one of the earlier posts you mentioned this:
Wdio launcher has some specifics, so you don't need to create steps using allure.createStep. Instead, every webdriver command will be recorded a step. If you want to create custom step – just create a custom command.

when i run my tests and generate the allure reports they are not grouped together. 
For example:
describe('test1')
- describe('childOfTest1')
-- it('childOfAboveDescribe')
-- it('childOfAboveDescribe')

- describe('childOfTest1')
-- it('childOfAboveDescribe')
-- it('childOfAboveDescribe')
-- it('childOfAboveDescribe')

instead they are just randomly placed in the allure reporter.
How can I organise this? Is there any reference on how to create custom steps? I am using wdio-allure-reporter

**Comment by just-boris** [comment]
@cheungkayip you have two `describe()` with the same name `childOfTest1`. From the point of Allure, it is the same test suite, that's why they merged together.

Of you want to see different groups in report, give them different names.
