### ISSUE TITLE
False positive report when using Mocha "retries" option

### ISSUE THREAD

**Issue by timonag** [allure-framework/mocha-allure-reporter#18]
I'm using Mocha's **retries** for e2e tests to rerun failed test case. For example:
```
"use strict";
var chai = require("chai");
var expect = chai.expect;

describe("Test suite", function(){
	this.retries(5);
	it("Test case 1", function(){
		expect(true).to.be.true()
	});
	it ("Test case 2", function(){
		expect(true).to.be.false()
	});
});
```
The problem is that the reporter produces 6 entries for the failed test case: first five in _passed_ state and the last one in _failed_.
I think that expected behaviour is to create only one report entry for a test case, which was repeated.

**Comment by just-boris** [comment]
Hello, thank you for your bug report.

Not it looks like an issue in the mocha itself. It should report only about first test start, but not restart.
I will try to send them a PR and will post a link here then.
