### ISSUE TITLE
Support features and stories

### ISSUE THREAD

**Issue by just-boris** [allure-framework/mocha-allure-reporter#3]
We need to inject allure API into tests, to allow users provide more info, such as descriptions or features/stories

**Comment by LeXuZZ** [comment]
it would be great!

**Comment by just-boris** [comment]
mocha-allure-reporter version 1.1.0 has been released. Now you have global `allure` object with set of useful methods to provide info from your tests. For instance, you can set feature and story by the following way:

```js
it("test in story", function() {
    allure.addLabel('feature', 'my feature');
    allure.addLabel('story', 'my story');
   //do your test code
});
```

**Comment by just-boris** [comment]
ProTip: you can set feature for a group of tests in `beforeEach` section as well

```
beforeEach(function() {
    allure.addLabel('feature', 'my feature');
    allure.addLabel('story', 'my story');
});
it("test 1", function() {});
it("test 2", function() {});
it("test 3", function() {});
```
all of these test cases will get feature info
