### ISSUE TITLE
 Cannot read property 'targetDir' of undefined when using mocha through gulp task

### ISSUE THREAD

**Issue by ezik** [allure-framework/mocha-allure-reporter#6]
Hi, I am a newbie in this field and trying to connect reports generating to my tests.
Gulp task code is:
```javascript
gulp.task('test', function() {
    return gulp
        .src(argv['test-src'] || 'tests/**/*.js')
        .pipe(mocha({
            timeout: config['mocha-timeout'],
            useColors: !argv['no-color'],
            slow: 10000,
            require: 'tests/test-helper.js',
            reporter: 'mocha-allure-reporter'
        }));
});
```
Then I start "gulp test" through console and get:
`Cannot read property 'targetDir' of undefined`

I tried to add following string components:
`reporter: 'mocha-allure-reporter --targetDir "./allure-results"'`

and
```
reporter: 'mocha-allure-reporter'
targetDir: './allure-results'
```
without any luck.

Can anyone describe how can I correctly notify reporter about results directory?

**Comment by pdoggyster** [comment]
You have to use the mocha reporterOptions.

gulp.task('test', function() {
    return gulp
        .src(argv['test-src'] || 'tests/**/*.js')
        .pipe(mocha({
            timeout: config['mocha-timeout'],
            useColors: !argv['no-color'],
            slow: 10000,
            require: 'tests/test-helper.js',
            reporter: 'mocha-allure-reporter',
            reporterOptions: {targetDir: 'allure-results'}
        }));
});

**Comment by ezik** [comment]
Wow, that helps!

Thank you very much.

**Comment by pdoggyster** [comment]
You're welcome but if you don't want to change then it need to download again this package to your node_modules and it will work well.
